language: php

php:
  - '5.6'

branches:
  only:
    - master
  
install:
  - composer install
  - composer update
  - php bin/console assets:install

deploy:
  - skip_cleanup: true

after_success:
  - ./deploy.sh
