language: php

php:
  - '5.6'

branches:
  only:
    - master
  
install:
  - composer install
  - composer update
  - php bin/console assets:install
  - php bin/console cache:clear -e prod

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true

env:
  FTP_FOLDER=quantified
