language: php

php:
  - '5.6'

branches:
  only:
    - master
  
install:
  - composer install
  - composer update
  - php bin/console assets:install

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
