core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

agregator:
    resource: "@AgregatorBundle/Resources/config/routing.yml"
    prefix:   /

google:
    resource: "@GoogleBundle/Resources/config/routing.yml"
    prefix:   /google

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login