# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    devCount:
                        password: $2y$12$ZifeDAvnMYOa6aDtDOMFPOZ9WbVzRJVE8v2urAqYgiPAN9s1NImB6
                        roles:    'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost:      12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

#        google:
#            anonymous: ~
#            oauth:
#                resource_owners:
#                    google:             "/login/check_google"
#                login_path:        /login_google
#                use_forward:       false
#                failure_path:      /login_google
#
#                oauth_user_provider:
#                    service: hwi_oauth.user.provider

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app, roles: IS_AUTHENTICATED_FULLY }
